version: '3.6'

services:
  api:
    image: quay.io/go-skynet/local-ai:latest
    environment:
      - DEBUG=true
      - MODELS_PATH=/models
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai" ]
    networks:
      - api_network

  chatgpt:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    ports:
      - 4000:3000
    environment:
      - 'OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXX'
      - 'OPENAI_API_HOST=http://api:8080'
    networks:
      - api_network

networks:
  api_network:
    driver: bridge