name: Deploy with Terraform

on:
  push:
    branches:
      - main

env:
  TF_BACKEND_STORAGE_ACCOUNT: "terraformstatestorage"
  TF_BACKEND_CONTAINER: "tfstate"
  TF_BACKEND_KEY: "example.tfstate"

jobs:
  deploy:
    runs-on: ubuntu-latest

    # env:
    #   TF_VAR_scaleway_access_key: ${{ secrets.TF_VAR_scaleway_access_key }}
    #   TF_VAR_scaleway_secret_key: ${{ secrets.TF_VAR_scaleway_secret_key }}
    #   TF_VAR_scaleway_project: ${{ secrets.TF_VAR_scaleway_project }}
    #   TF_VAR_scaleway_region: pl-waw
    #   TF_VAR_scaleway_zone: pl-waw-1

    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Initialize Terraform
        run: |
          terraform -chdir=./terraform init

      - name: Terraform Validate
        run: terraform -chdir=./terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=./terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=./terraform apply tfplan
        env:
          TF_APPROVE: "yes"
