name: Deploy with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: "./terraform"
    env:
      TF_VAR_scaleway_access_key: ${{ secrets.TF_VAR_SCALEWAY_ACCESS_KEY }}
      TF_VAR_scaleway_secret_key: ${{ secrets.TF_VAR_SCALEWAY_SECRET_KEY }}
      TF_VAR_scaleway_project: ${{ secrets.TF_VAR_SCALEWAY_PROJECT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Login
        id: login
        run: terraform login ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Refresh
        id: refresh
        run: terraform refresh -no-color
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=plan -input=false
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color -auto-approve
        continue-on-error: false
