name: Deploy with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: "./terraform"
    env:
      TF_VAR_scaleway_access_key: ${{ secrets.TF_VAR_SCALEWAY_ACCESS_KEY }}
      TF_VAR_scaleway_secret_key: ${{ secrets.TF_VAR_SCALEWAY_PROJECT }}
      TF_VAR_scaleway_project: ${{ secrets.TF_VAR_SCALEWAY_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=plan -input=false
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color apply -auto-approve -input=false
        continue-on-error: false
